### ISSUE TITLE
Property file loading issue

### ISSUE THREAD

**Issue by abhijitkaranjkar89** [airavata-courses/TeamIndra#10]
I doubt if this thing works, : <value>file:./conf/override_config.properties</value>
As your resource folder is in build path.
Faced some issue setting up the project on local so could not try.
Also, always try to give the absolute path instead of relative path. Majority of the projects use absolute path.

**Comment by bhandaresagar** [comment]
Hi abhijit,

Please check github for milestone 1 submission folder. It has executable
jar, sample conf file and instructions to run the jar.

The resource folder is always in build path for any maven based project.
About the configuration file, its good practice to have to conf files one
inside project and other override file configurable by user.

The absolute paths should be used when its installable software and  is
when you are well known about installation machine file system. In this
case, the user can run current jar on Linux or windows machine from any
location.  so conf file should be searched in current directly only. That
explains the relative path given.

Please let me know if you face problems in setting up project locally.

Thanks,
Sagar
