### ISSUE TITLE
User does not receive the job-related log files upon job completion

### ISSUE THREAD

**Issue by a2l007** [airavata-courses/TeamIndra#2]
Issue: User was able to submit the job and monitor the status of the job, but on job completion, the user does not receive the email containing the job-related log files.

Steps to reproduce: 
1. Modify the override_config.properties properties to include user-specific data. 
2. Copy the helloapp and sortapp folders to the user scratch directory on Karst
3. Submit the job by running the jar.

**Comment by bhandaresagar** [comment]
fixed the issue
