### ISSUE TITLE
Scheduler process does not terminate even after job completion

### ISSUE THREAD

**Issue by a2l007** [airavata-courses/TeamIndra#3]
The job submission user interface requests for the user input to either monitor the job or terminate the scheduler. 
Once a job is complete, the job status invoked via qstat may show the completed status for some time after which the job status would be empty.
When qstat no longer returns an output status for the completed job and the user attempts to monitor the job via your interface, there would be no output provided to the user as qstat does not return anything.
I feel that in such a scenario, your process could check the existence of output from qstat and terminate itself notifying the user. 
This may not be an issue, but I feel this could be checked.

**Comment by bhandaresagar** [comment]
not applicable in recent version
