### ISSUE TITLE
Milestones 2 and 3 graded, Milestone 4 has issues

### ISSUE THREAD

**Issue by marpierc** [airavata-courses/TeamIndra#34]
Hi Team Indra,

With your help yesterday, we resolved the issues for PM2 and PM3. As discussed, you still need to add BR2 submission of GROMACS to your PM4 submission. PM4 also requires a pointer to your description of your metadata management schema design.

**Comment by marpierc** [comment]
These issues are still open.

**Comment by pratishmerchant** [comment]
Hello Marlon,

We have pushed the code in M4 where we can specify the the server name  in
config file. Kindly let us know if you still cant push code to BR2.

Regards,
Pratish

**Comment by marpierc** [comment]
So I would need to change karst to bigred2?  But the gateway only allows 1 resource at a time?

**Comment by pratishmerchant** [comment]
Hello Marlon ,

Yes , at one connection we can run only on one server. The milestone didnt
specify being able to simultaneously send to both servers , hence we went
ahead with this implementation.

Please let us know if we missed something , so we can quickly make the
desired changes.

Regards,
Pratish.

On Mon, May 2, 2016 at 12:27 PM, Marlon Pierce notifications@github.com
wrote:

> So I would need to change karst to bigred2? But the gateway only allows 1
> resource at a time?
> 
> From: ajinkya-dhamnaskar <notifications@github.com<mailto:
> notifications@github.com>>
> Reply-To: airavata-courses/TeamIndra <reply@reply.github.com<mailto:
> reply@reply.github.com>>
> Date: Monday, May 2, 2016 at 12:25 PM
> To: airavata-courses/TeamIndra <TeamIndra@noreply.github.com<mailto:
> TeamIndra@noreply.github.com>>
> Cc: marpierc <marpierc@iu.edu<mailto:marpierc@iu.edu>>, Author <
> author@noreply.github.commailto:author@noreply.github.com>
> Subject: Re: [airavata-courses/TeamIndra] Milestones 2 and 3 graded,
> Milestone 4 has issues (#34)
> 
> Hello Marlon,
> 
> We have pushed the code in M4 where we can specify the the server name in
> config file. Kindly let us know if you still cant push code to BR2.
> 
> Regards,
> Pratish
> On May 2, 2016 12:08 PM, "Marlon Pierce" <notifications@github.com<mailto:
> notifications@github.com>> wrote:
> 
> > These issues are still open.
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/airavata-courses/TeamIndra/issues/34#issuecomment-216278694>
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub<
> https://github.com/airavata-courses/TeamIndra/issues/34#issuecomment-216283997>
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/airavata-courses/TeamIndra/issues/34#issuecomment-216284374

## 

Regards,
Pratish Merchant

**Comment by bhandaresagar** [comment]
Hi Professor,
We have fixed this problem and changes are now part of master branch. Could you please update the grades for milestone 4.

**Comment by marpierc** [comment]
In Gateway Web Service/src/main/resources/config.properties, how do I specify both BR2 and Karst?
