### ISSUE TITLE
Config File uploaded with SSH key passphrase value

### ISSUE THREAD

**Issue by arpiagariu** [airavata-courses/TeamIndra#4]
Hi TeamIndra,

SSHKEY.PassPhrase value is mentioned in the config.properties file at the following location: TeamIndra/Gateway First Tier/src/main/resources/config.properties.

Anyone who gain access to your console would be able to log in to remote systems using your keys. Or what if you lost your key, the finder would be able to access every system on which you installed your public key.

**Comment by bhandaresagar** [comment]
fixed this issue https://github.com/airavata-courses/TeamIndra/commit/6eedcb7f31e2959f0769834ed6ade05058387b20
