### ISSUE TITLE
Could have automated putting the c files on karst server

### ISSUE THREAD

**Issue by patel99** [airavata-courses/TeamIndra#5]
Hi TeamIndra,

[Note: This is a suggestion rather than issue ]
You could have automated the task of putting the c files for helloapp and sortapp. Since you are already copying the shell file from your client machine to the karst server, in the same way you could have automated the task of copying those files on the karst server as well

Pratik Patel

**Comment by sanketmhaiskar** [comment]
It was just a design consideration for now. But yes we could have automated the task of putting the c files also. Thank you for the suggestion.
